### ISSUE TITLE
Buggy for night

### ISSUE THREAD

**Issue by Lordfinix** [vladrevers/OmniJaws#1]
At night the weather condition should be clear, but it shows sunny instead. Rest all super good

**Comment by vladrevers** [comment]
@Lordfinix I don't quite understand the issue. Do you mean that the sun icon is displayed at night instead of the moon?
On which weather provider exactly?

**Comment by Lordfinix** [comment]
No the icon is alryt iam talking about weather condition 
![Screenshot_20221202-182226_Kiwi Browser~2](https://user-images.githubusercontent.com/116871754/205297382-502b88e0-8779-47db-8205-e23a132a8671.png)

Here ryt now its cloudy but at night it shows sunny instead of clear.

**Comment by vladrevers** [comment]
While I’m closing. I need more information and more clarity. Regarding the "description", it depends where your firmware gets it from, and there are two options..
1) These are just descriptions of the icon, and then it is most often useless or inaccurate/inflexible.
2) It turns out with OmniJaws, then it depends on the weather provider. Most provide a separate icon and descriptions, if this option is used for most providers everything should be fine.
