### ISSUE TITLE
Android compatibility issues  安卓兼容性问题 

### ISSUE THREAD

**Issue by no1uvbsvname** [vladrevers/OmniJaws#2]
What is the minimum compatible Android version? What is the most compatible Android version?
Can Android 4 (SDK 14) and above (including Android 4) work properly?

This is my translation with google translate software, if there is something wrong please point it out, I apologize.

请问最低兼容的安卓版本是多少? 最高兼容的安卓版本是多少?
安卓4(sdk14) 以上的版本(包括安卓4)可以正常使用吗?

这是我用谷歌翻译软件翻译的,如果有不对的地方请指出来,我很抱歉.

**Comment by vladrevers** [comment]
@no1uvbsvname It's a fork so I don't know for sure. Now there is a target version of Android 7.1 (25 sdk). Since the weather icons are vector and support libraries are not used, it will not work lower than Android 5, but if necessary, you can try replacing the icons with bitmap ones, and downgrading the minSdk to the version you need.
