### ISSUE TITLE
Version for Android 13

### ISSUE THREAD

**Issue by blackeangel** [vladrevers/OmniJaws#3]
Version for Android 13 does not work on Lineage OS 20. Widget does not watching.

**Comment by vladrevers** [comment]
Yes, as it turns out OmniJaws for Android 13 has a dependency to the system where there is integration with it. Now in the hat apk for crDroid, in principle to adapt to other firmware on request is not a problem.... But LineageOS, as well as AOSP this does not apply, there are no necessary classes in the system.

But the widget should work from the regular version (which is in releases).
